baseurl = "http://www.it.uu.se/education/course/homepage/introit/ht16/" 
languageCode = "en-us"
title = "1DT051/2016"
theme = "hugo-material-docs"
# theme = "default"

metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

PygmentsCodeFences = false
PygmentsStyle = "default"


[params]
	# General information
	author = "Karl Marklund"
  # 	description = "A material design theme for documentations."
	copyright = "Released under the MIT license"

  course_code = "1DT051"
  course_name = "Introduktion till informationsteknologi"
  course_year = "2016"

	# Repository
  #	provider = "GitHub"
  # repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	# version = "1.0.0"
  # logo = "images/logo.png"
	favicon = ""

  ##	permalink = "#"

	# Custom assets
	custom_css = ["css/material-tweaks.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "light-green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "uu-it-teaching/1DT051-2016-homepage"

  name = "Programmering"
  url  = "programming/index"



#### Resurser

[[menu.main]]
  name = "Start"
  weight = 10

[[menu.main]]
  name = "Syfte och översikt"
  parent = "Start"
  url = "./"
  weight = 11

[[menu.main]]
  name = "Python i korthet"
  parent = "Start"
  url = "python-i-korthet/"
  weight = 12

[[menu.main]]
  name = "Övriga resurser"
  parent = "Start"
  url = "resources/"
  weight = 13

#### Part 1

[[menu.main]]
  name = "Del 1"
  weight = 20

[[menu.main]]
  name = "Syfte och överskikt"
  identifier = "part-1-about"
  parent = "Del 1"
  url    = "programming/part-1/"
  weight = 21 

[[menu.main]]
  name = "Uppgifter"
  identifier = "part-1-assignment"
  parent = "Del 1"
  url    = "programming/part-1/assignment/"
  weight = 22

[[menu.main]]
  name = "Redovisning"
  identifier = "part-1-grading"
  parent = "Del 1"
  weight = 23
  url    = "programming/part-1/grading/"


#### Part 2

[[menu.main]]
  name = "Del 2"
  weight = 30

[[menu.main]]
  name = "Syfte och översikit"
  identifier = "part-2-about"
  parent = "Del 2"
  url    = "programming/part-2/"
  weight = 31

[[menu.main]]
  name = "Workshop"
  identifier = "part-2-workshop"
  parent = "Del 2"
  url = "programming/part-2/workshop"
  weight = 32

[[menu.main]]
  name = "Uppgifter"
  identifier = "part-2-assignment"
  parent = "Del 2"
  url    = "programming/part-2/assignment/"
  weight = 33

[[menu.main]]
  name = "Frivillig fördjupning"
  parent = "Del 2"
  url = "programming/part-2/optional/"
  weight = 34

[[menu.main]]
  name = "Handledning"
  parent = "Del 2"
  url = "programming/part-2/tutoring/"
  weight = 35

[[menu.main]]
  name = "Redovisning"
  parent = "Del 2"
  url = "programming/part-2/grading/"
  weight = 35

#### Part 3

[[menu.main]]
  name = "Del 3"
  weight = 40

[[menu.main]]
  name = "Syfte och översikt"
  identifier ="part-3-about"
  parent = "Del 3"
  url    = "programming/part-3/"
  weight = 41

[[menu.main]]
  name = "Uppgifter"
  identifier = "part-3-assignment"
  parent = "Del 3"
  url    = "programming/part-3/assignment/"
  weight = 42

#### Projekt

[[menu.main]]
  name = "Projekt"
  weight = 50

[[menu.main]]
  name = "Syfte och översikt"
  identifier = "project-about"
  parent = "Projekt"
  url    = "programming/project/"
  weight = 51

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
